Adding back original installation text
knative-sandbox/kn-plugin-quickstart pull request #65
Opened 2021-07-28 14:15 UTC by psschwei

# Changes

- Restores original install text from the KonK script, and adds a little formatting to some other messages

/kind enhancement

Fixes #54

2021-07-28 20:34 UTC, csantanapr requested changes
I think we should keep the versions printed

2021-07-28 20:34 UTC, csantanapr commented on pkg/install/install.go
> +	fmt.Println("🕸️ Instlling Kourier networking layer...")
I really want to see the versions being printed

2021-07-28 20:34 UTC, csantanapr commented on pkg/install/install.go
> +	fmt.Println("🕸️ Instlling Kourier networking layer...")
```suggestion
	fmt.Println("🕸️ Installing Kourier networking layer...")
```

2021-07-28 20:34 UTC, csantanapr commented on pkg/install/install.go
> +	fmt.Println("🍿 Installing Knative Serving...")
let's keep the version printed. 🙏

2021-07-28 20:56 UTC, psschwei commented
> I think we should keep the versions printed

sounds good to me

2021-07-28 22:23 UTC, csantanapr commented
perfect
/lgtm

2021-07-28 22:24 UTC, csantanapr approved these changes

2021-07-28 22:24 UTC, merged

2021-07-29 16:16 UTC, psschwei commented
/cherry-pick release-0.1